# Lambda Functions - Lab

## Introduction|

In this lab, you'll get some hands on practice creating and using lambda functions.

## Objectives
You will be able to:
* Understand what lambda functions are and why they are useful
* Use lambda functions to transform data within lists and DataFrames

## Lambda Functions

In [2]:
import pandas as pd
df = pd.read_csv('Yelp_Reviews.csv')
df.head(5)

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg

# Simple Arithmetic

Use a lambda function to create a new column called 'stars_squared' by squarring the stars column.

In [9]:
df['stars_squared'] = df['stars'].map(lambda x: x**2)

# Dates
Select the month from the date string using a lambda function.

In [14]:
df['date'][0][5:7]

'11'

In [24]:
#df['date'].map(lambda x: x[-5:-3]).head()
df['date'].map(lambda x: x[5:7]).head()

0    11
1    10
2    09
3    02
4    06
Name: date, dtype: object

# What is the average number of words for a yelp review?
Do this with a single line of code!

In [45]:
len(df['text'][4].split())

32

In [41]:
df['text'].map(lambda x: len(x.split())).mean()

77.06551724137931

# Create a new column for the number of words in the review.

In [42]:
df['review_words'] = df['text'].map(lambda x: len(x.split()))

In [57]:
df.head()

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,review_words,review_length
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,58,Medium
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,30,Short
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25,30,Short
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1,82,Long
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25,32,Short

## Rewrite the following as a lamda function. Create a new column 'Review_Length'

In [5]:
def rewrite_as_lambda(value):
    if len(value) < 50:
        return 'Short'
    elif len(value) < 80:
        return 'Medium'
    else:
        return 'Long'
#Hint: nest your if, else conditionals

In [54]:
df['review_length'] = df['review_words'].map(lambda x: 'Short' if (x < 50) else 'Medium' if x >=50 and x < 80 else 'Long')

In [58]:
df.head(15)

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,review_words,review_length
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,58,Medium
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,30,Short
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25,30,Short
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1,82,Long
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25,32,Short
5,11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0,HkYqGb0Gplmmk-xlHTRBoA,1,The score should be negative. Its HORRIBLE. Th...,0,NhOc64RsrTT1Dls50yYW8g,1,49,Short
6,12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0,RgqWdZA4xR023iP3T6jVfA,5,I went there twice and I am pretty happy with ...,0,NhOc64RsrTT1Dls50yYW8g,25,21,Short
7,19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0,51RHs_V_fjuistnuKxNpEg,5,Finally! After trying many Mexican restaurants...,0,5ngpW5tf3ep680eG1HxHzA,25,70,Medium
8,25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0,alI_kRKyEHfdHibYGgtJbw,1,I have to write a review on the Fractured Prun...,0,Fc_nb6N6Sdurqb-rwsY1Bw,1,131,Long
9,26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0,85DRIjwPJOTb4q0qOlBstw,1,I wish i could tell you all about the food but...,1,Fc_nb6N6Sdurqb-rwsY1Bw,1,112,Long
10,27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0,GbiLIKmQPVCBtdNkTVdVSA,5,Wonderful! One of my favorite places. BBQ is e...,0,G22ITfVETYHtIhnn5lLRrQ,25,19,Short
11,28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0,UaHgsL0xS4UnJ_iKqeOk_w,5,The price is about the same as Quizinos. The s...,0,FjH3TH8OvHGLNEbzdEYlNg,25,28,Short
12,29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0,c4zzAD1S6721Fh-acCBy-g,4,The food was ok. You get a lot of food for the...,0,FjH3TH8OvHGLNEbzdEYlNg,16,20,Short
13,30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0,TTBwocu2mvqJFJrwmJN0Sw,5,The staff were friendly and helpful. The food ...,1,FjH3TH8OvHGLNEbzdEYlNg,25,15,Short
14,31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0,-CresnnXQSHrQ85Ogm-Pqw,5,The staff were very helpful. We painted potter...,0,FjH3TH8OvHGLNEbzdEYlNg,25,28,Short

In [59]:
df['review_length']==50]

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,review_words,review_length
138,575,VRwT0pscR5vESCrAnUpNwQ,0,2015-06-30,0,qO81z1KiEviyr2TEVOXaeg,2,The fish taco is really good. \r\n\r\nBurrito ...,0,kBNFdviedCPFWyR-wVaAzw,4,50,Medium
160,613,BLp6atZ7ydioAIVkKlmAGg,0,2016-02-13,0,zAasT5y0d1p28bNBXzIcFA,5,Best cocktails in Vegas. You can add a shot or...,0,oZOBAtPYVUq724Wywoh5kg,25,50,Medium
317,1151,7Tp53xZh1ypd2wbudP6Qcw,0,2012-08-28,0,PaAhCPNps4JWpMZwcqHLAw,4,I'm always surprised at how hard it is to find...,0,IKChsSm17dLG0mTHjFiDLg,16,50,Medium
347,1320,6NwkKX8VvN3Nnn-ANISBrQ,0,2015-04-16,0,kSGa7LDrJ1XoAIl0V3vWNA,5,Amy H. was great. She was very accommodating a...,1,gENP-H3lLEfQ_7vHgswGjg,25,50,Medium
388,1490,b7pkopqvDr7A7S7hlqp6cw,0,2013-03-10,0,nbXpWZWTOog4Zuumb1DJtQ,5,Food is so good! They have a new menu out with...,1,PwOYstqW_MVUbV4qWonCEQ,25,50,Medium
501,1844,hI_WID6sP7EOgPeFFJPPwQ,0,2015-09-21,0,nBikv36sTDfmEZMJqCnuww,2,What a disappointment! I hadn't been able to ...,0,uU_ol_n14rgh8kuuZ--WSQ,4,50,Medium
601,2107,m8o3OrY0DWfqvk820EyrxQ,0,2017-02-26,0,tUm_W7b0r2iCgj2hovqHtg,5,Computer Doctor BG did a thorough diagnosis of...,0,Ck6CDY0rcGfadIWXRJ5Z0Q,25,50,Medium
679,2341,ABJjxuO6oh5D9R48-eAUdQ,0,2012-04-09,0,kbh-PFHAwxDRejuVv7kRwA,2,Food was not bad for the price but the atmosph...,0,RZ0Ny03o_5h3AtxCLcS_qw,4,50,Medium
696,2408,2oEXQryBIq6uFpbMWt7mAA,0,2017-01-02,0,Q-kcYWI5iQUOVNY7eBykpQ,5,I used womb wellness to find a birth and postp...,0,sreDEUoT6peIM1QdZEbg7A,25,50,Medium
743,2518,oyCRc4Zs2RkKOHy9IAa3wg,0,2016-07-04,0,G-7mZq8TYKeUsEma9vy4jQ,5,Excellent breakfast food and staff!!!! Great f...,0,VEHccrkpl1O_dGAn_d_TTA,25,50,Medium
904,3133,DFeEJf8h04q3KwRVWUsoMQ,0,2016-03-27,0,CfHwbKOWVN6UGax8NwnWmQ,1,Worst service ever and all of our food was eit...,2,ZcgHNMGUKp-J9hRqgoDx6A,1,50,Medium
923,3184,qIRqFlmvHDRe7kWBAsuVnQ,0,2017-11-24,0,uS_0qETniDQC1RS_cB6ubA,4,wow I was just craving for spicy noodle then I...,0,Bm-ybn_5ibNaYGn8cjaQkw,16,50,Medium
1055,3724,zw9_mqWBn1QCfZg88w0Exg,0,2014-04-17,0,Y7MArYMgk6ToWIuKrD9-Kg,5,Great food and wonderful service!!!! The manag...,0,gfK3WCNiD3Mq4BUPVfT4GA,25,50,Medium
1192,4213,sBrrWO-Nv7imsqU0e5504Q,0,2016-07-13,0,E4S2OJpQorhXbtw0eIhz4A,5,Came here around lunch time. I ordered ahead o...,2,ic9zIsm7zoxUm3Axyegx8g,25,50,Medium
1214,4305,QdganL5AW9E_fNoRVroLig,0,2014-03-11,1,wbjm7ChpSB0EbL9Umun2lA,1,Had duck fried rice which was full of small cr...,1,jNz3ic5TdcDIZJtx7iM5wQ,1,50,Medium
1265,4499,sgeH1aWYynK1BQiouCTMtw,1,2013-01-14,0,iR0CTy7yDzjDZzzDhOhmew,5,Great place for breakfast and lunch. Friendly ...,1,gVmsL-FroEEx5mZSRqEa4Q,25,50,Medium
1453,88,gxEkxkqQrrK62DJnXxXDLg,0,2016-03-06,0,tTc81A4aHV4DDtkFVG8RNw,3,"Bbq, bacon burger is awesome! Salads are grea...",0,0pf5VuzE4_1pwj5NJHG5TQ,9,50,Medium
1566,4816,j3SHAiF8OIlY3kUPnAAlKw,0,2010-02-02,0,Y4csu2bbvYcQyIsaKEyf8w,4,I love the food at House of Leng. it's a grea...,1,q8U1dGxFJ9fQy-NMOFUCJA,16,50,Medium
1597,1825,sd4BuC4Om6WuvnP87ZS8Og,0,2017-06-04,0,IORR2rH64Jv-OAI3RH_Btg,5,Quaint little local cafe! I had the Dirty Lond...,0,Wzsduf0vEmr-Ih1H0Stvww,25,50,Medium
1651,3742,NcrasPRJ3xm0K7JPxLFBGA,0,2015-05-08,0,yd1ibc9MwzTudwVlmr37GA,5,By far one of the best 24 hour tropical smooth...,0,4oUR0OVCDfXPfGNXd8nGdQ,25,50,Medium
1738,2396,h6f3QbR0n0fpS2Tu9MJJTw,0,2013-04-28,0,B8OigiOWqtJYT3PvJmnBkg,5,We went with a big group so we go to try lots ...,0,KKgHnDVFe8y5F7BI7njrFg,25,50,Medium
1749,560,ihW5mCeFuzouTzIIduNEFQ,1,2014-05-04,1,PO-N4Vz3WE-x9mrCPy-D6w,4,Great food at a great price! \r\nI had brunch ...,2,71_41E7uuPr0_Gm6y1qbqA,16,50,Medium
1802,1490,b7pkopqvDr7A7S7hlqp6cw,0,2013-03-10,0,nbXpWZWTOog4Zuumb1DJtQ,5,Food is so good! They have a new menu out with...,1,PwOYstqW_MVUbV4qWonCEQ,25,50,Medium
1850,2712,TT658qQinO6MBHP9q7rJ8w,0,2016-09-27,0,z2dq9-gPjCxgYy6vBYiAag,4,Food was good. But what was better was the ser...,0,7lxEzQEcVTsuRebyA7hfhg,16,50,Medium
1860,3256,zUgDrRtGvK5ZTFlHCsTHwA,0,2014-09-17,0,fRZr6q-a2GOuu3jl-de-bg,4,The best pizza I have found in the valley that...,0,Vzm4fJnIxmgSKTgR1-0uzA,16,50,Medium
2362,4034,KWf3sEG-S4xY0RgiwGprvA,3,2015-07-13,4,RV51yOy28YOz9E_oA4dcnw,1,This is the worst hairdresser I've ever met! H...,3,8Du42UNHof7va5isCFtOig,1,50,Medium
2405,3184,qIRqFlmvHDRe7kWBAsuVnQ,0,2017-11-24,0,uS_0qETniDQC1RS_cB6ubA,4,wow I was just craving for spicy noodle then I...,0,Bm-ybn_5ibNaYGn8cjaQkw,16,50,Medium
2410,3133,DFeEJf8h04q3KwRVWUsoMQ,0,2016-03-27,0,CfHwbKOWVN6UGax8NwnWmQ,1,Worst service ever and all of our food was eit...,2,ZcgHNMGUKp-J9hRqgoDx6A,1,50,Medium
2448,1151,7Tp53xZh1ypd2wbudP6Qcw,0,2012-08-28,0,PaAhCPNps4JWpMZwcqHLAw,4,I'm always surprised at how hard it is to find...,0,IKChsSm17dLG0mTHjFiDLg,16,50,Medium
2498,4305,QdganL5AW9E_fNoRVroLig,0,2014-03-11,1,wbjm7ChpSB0EbL9Umun2lA,1,Had duck fried rice which was full of small cr...,1,jNz3ic5TdcDIZJtx7iM5wQ,1,50,Medium
2530,1751,6YrmJ_pxLSTabcM_FFZhlQ,0,2016-04-28,0,7CsHSm5Dvy-vkXTutiHZ4A,3,I go here for one thing only. CORN DOGS!\r\nIf...,0,UqYtHGxXJK9s4ltIm6Uw_w,9,50,Medium

# Level Up: Dates Adavanced!
<img src="date_format_map.png" width=500>  

Overwrite the date column by reordering the month and day from YYYY-MM-DD to DD-MM-YYYY. Try to do this using a lambda function.

In [ ]:
#Your code here

## Summary

Great! Hopefully you're getting the hang of lambda functions now! It's important not to overuse them - it will often make more sense to define a function so that it's reusable elsewhere. But whenever you need to quickly apply some simple processing to a collection of data you have a new technique that will help you to do just that. It'll also be useful if you're reading someone elses code that happens to use lambdas.